spring:
  application:
    name: user-service
  datasource:
    username: pguser
    password: pgpassword
    url: jdbc:postgresql://localhost:5499/auth
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jwt
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
