spring:
  application:
    name: user-service
  r2dbc:
    username: pguser
    password: pgpassword
    url: r2dbc:postgresql://localhost:5499/auth
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5499/auth
  jwt:
    secret: ${jwt_secret}
    expiration: 2_592_000_000 #30Days
    accessExpiration: 3_600_000 # 1 hour
  cloud:
    gateway:
      enabled: true
      routes:
        - id : NEWS-SERVICE
          uri: http://localhost:8888
          predicates:
            - /news/**
